<a href="https://colab.research.google.com/github/AbdulrahmanB-25/Machine_Learning_Competition/blob/main/MetroStationDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
  import pandas as pd
  import numpy as np
  import matplotlib.pyplot as plt
  import seaborn as sns

  sns.set_style("whitegrid")

In [2]:
df = pd.read_csv("metro-stations-in-riyadh-by-metro-line-and-station-type-2024.csv")
df.head()

,رقم العنصر الداخلي,رمز محطة المترو,Station name,اسم المحطة,رقم خط المترو,Metro line name,اسم مسار القطار,رمز نوع المحطة,Station type,نوع المحطة,تسلسل المحطات,Comments,التعليقات,الإحداثيات الجغرافية,geo_point_2d
0,40,S02,Dr Sulaiman Al Habib,د.سليمان الحبيب,Line1,Blue line,المسار الأزرق,1,Elevated,مرتفع,2,NaN,NaN,"{""coordinates"": [46.62654386725997, 24.8115537...","24.81155379383345, 46.62654386725997"
1,49,S03,KAFD,المركز المالي,Line1,Blue line,المسار الأزرق,1,Elevated,مرتفع,3,NaN,NaN,"{""coordinates"": [46.64364447641301, 24.7680039...","24.76800392512061, 46.64364447641301"
2,18,S04,Al Murooj,المروج,Line1,Blue line,المسار الأزرق,4,Deep Underground,تحت الأرض على عمق كبير,4,NaN,NaN,"{""coordinates"": [46.65422135694412, 24.7547460...","24.75474607607529, 46.65422135694412"
3,56,S05,King Fahad District,حي الملك فهد,Line1,Blue line,المسار الأزرق,4,Deep Underground,تحت الأرض على عمق كبير,5,NaN,NaN,"{""coordinates"": [46.65932671648558, 24.7449144...","24.74491442205136, 46.65932671648558"
4,24,S08,Al Wurud 2,الورود 2,Line1,Blue line,المسار الأزرق,4,Deep Underground,تحت الأرض على عمق كبير,8,NaN,NaN,"{""coordinates"": [46.67112888545265, 24.7217274...","24.72172740595173, 46.67112888545265"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   رقم العنصر الداخلي    94 non-null     int64
 1   رمز محطة المترو       94 non-null     object
 2   Station name          94 non-null     object
 3   اسم المحطة            94 non-null     object
 4   رقم خط المترو         94 non-null     object
 5   Metro line name       94 non-null     object
 6   اسم مسار القطار       94 non-null     object
 7   رمز نوع المحطة        94 non-null     int64
 8   Station type          94 non-null     object
 9   نوع المحطة            94 non-null     object
 10  تسلسل المحطات         94 non-null     int64
 11  Comments              10 non-null     object
 12  التعليقات             10 non-null     object
 13  الإحداثيات الجغرافية  94 non-null     object
 14  geo_point_2d          94 non-null     object
dtypes: int64(3), object(12)
memory usage: 11.1+ KB

In [4]:
df.isnull().sum()

رقم العنصر الداخلي       0
رمز محطة المترو          0
Station name             0
اسم المحطة               0
رقم خط المترو            0
Metro line name          0
اسم مسار القطار          0
رمز نوع المحطة           0
Station type             0
نوع المحطة               0
تسلسل المحطات            0
Comments                84
التعليقات               84
الإحداثيات الجغرافية     0
geo_point_2d             0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [8]:
import re

df = df.loc[:, df.columns.str.contains(r'[a-zA-Z0-9_]')]
print(df.columns)

Index(['Station name', 'Metro line name', 'Station type', 'Comments',
       'geo_point_2d'],
      dtype='object')

In [10]:
df.drop(columns=['Comments'], inplace=True)

In [11]:
df.head()

,Station name,Metro line name,Station type,geo_point_2d
0,Dr Sulaiman Al Habib,Blue line,Elevated,"24.81155379383345, 46.62654386725997"
1,KAFD,Blue line,Elevated,"24.76800392512061, 46.64364447641301"
2,Al Murooj,Blue line,Deep Underground,"24.75474607607529, 46.65422135694412"
3,King Fahad District,Blue line,Deep Underground,"24.74491442205136, 46.65932671648558"
4,Al Wurud 2,Blue line,Deep Underground,"24.72172740595173, 46.67112888545265"