<a href="https://colab.research.google.com/github/AbdulrahmanB-25/Machine_Learning_Competition/blob/main/ML_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/AbdulrahmanB-25/Machine_Learning_Competition/refs/heads/main/Riyadh_Master_Dataset.csv'

# Load the dataset
df = pd.read_csv(url)

# Preview the data
df.head()

,neighborhood,property_id,price,area,category,lat,lng,dining_cafe,med_facilities,health_retail,...,pedestrian,resort_rural_retreats,gov_civil,malls_shopping,Fiber_Available,FWA_Available,Mobile_Available,connectivity_score,bus_count,metro_count
0,2nd Industrial City,1,4500.0,160.0,1,24.557812,46.862682,46,2,1,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
1,2nd Industrial City,2,17000.0,150.0,1,24.548426,46.866436,46,2,1,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
2,2nd Industrial City,3,1500000.0,750.0,2,24.555798,46.860222,46,2,1,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
3,2nd Industrial City,4,1000000.0,600.0,2,24.557178,46.864990,46,2,1,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
4,2nd Industrial City,5,1200000.0,600.0,2,24.554862,46.861086,46,2,1,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0

In [2]:
print(df.shape)

(345723, 27)

In [3]:
print(df.columns.tolist())

['neighborhood', 'property_id', 'price', 'area', 'category', 'lat', 'lng', 'dining_cafe', 'med_facilities', 'health_retail', 'fitness_care', 'edu_primary', 'edu_higher', 'religious', 'essential_retail', 'parks_green', 'sports_play', 'pedestrian', 'resort_rural_retreats', 'gov_civil', 'malls_shopping', 'Fiber_Available', 'FWA_Available', 'Mobile_Available', 'connectivity_score', 'bus_count', 'metro_count']

In [5]:
# keep only numeric columns
df_numeric = df.select_dtypes(include=["int64", "float64"])

df_numeric.head()

,property_id,price,area,category,lat,lng,dining_cafe,med_facilities,health_retail,fitness_care,...,pedestrian,resort_rural_retreats,gov_civil,malls_shopping,Fiber_Available,FWA_Available,Mobile_Available,connectivity_score,bus_count,metro_count
0,1,4500.0,160.0,1,24.557812,46.862682,46,2,1,0,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
1,2,17000.0,150.0,1,24.548426,46.866436,46,2,1,0,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
2,3,1500000.0,750.0,2,24.555798,46.860222,46,2,1,0,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
3,4,1000000.0,600.0,2,24.557178,46.864990,46,2,1,0,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0
4,5,1200000.0,600.0,2,24.554862,46.861086,46,2,1,0,...,0,0,9,4,0.0,1.0,1.0,2.0,53,0

In [6]:
# drop columns that should not be used in PCA
cols_to_drop = ["property_id"]  # ID column, not useful
df_numeric = df_numeric.drop(columns=cols_to_drop, errors="ignore")

# check missing values
print(df_numeric.isnull().sum())

price                      0
area                       0
category                   0
lat                        0
lng                        0
dining_cafe                0
med_facilities             0
health_retail              0
fitness_care               0
edu_primary                0
edu_higher                 0
religious                  0
essential_retail           0
parks_green                0
sports_play                0
pedestrian                 0
resort_rural_retreats      0
gov_civil                  0
malls_shopping             0
Fiber_Available          131
FWA_Available            131
Mobile_Available         131
connectivity_score       131
bus_count                  0
metro_count                0
dtype: int64

In [7]:
# fill with mean
df_numeric = df_numeric.fillna(df_numeric.mean())

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(df_numeric)

print(X_scaled.shape)

(345723, 25)

In [9]:
from sklearn.decomposition import PCA

pca = PCA()
X_pca = pca.fit_transform(X_scaled)

# explained variance
explained_variance = pca.explained_variance_ratio_

print(explained_variance)

[2.70004807e-01 1.91767892e-01 8.75670601e-02 7.20095293e-02
 5.74309796e-02 5.45690320e-02 4.19301338e-02 3.72064392e-02
 3.42272429e-02 3.08019457e-02 2.64010559e-02 1.93790398e-02
 1.56262345e-02 1.39555843e-02 1.26875852e-02 9.46274901e-03
 6.94817448e-03 5.91120623e-03 4.52836960e-03 3.71640524e-03
 1.86579306e-03 1.48216577e-03 5.20575157e-04 3.43373506e-16
 0.00000000e+00]

In [10]:
import numpy as np

cumulative_variance = np.cumsum(explained_variance)

print(cumulative_variance)

[0.27000481 0.4617727  0.54933976 0.62134929 0.67878027 0.7333493
 0.77527943 0.81248587 0.84671312 0.87751506 0.90391612 0.92329516
 0.93892139 0.95287698 0.96556456 0.97502731 0.98197548 0.98788669
 0.99241506 0.99613147 0.99799726 0.99947942 1.         1.
 1.        ]

In [11]:
pca = PCA(n_components=13)

X_pca = pca.fit_transform(X_scaled)

print(X_pca.shape)

(345723, 13)

In [12]:
pca_columns = [f"PC{i+1}" for i in range(13)]

df_pca = pd.DataFrame(X_pca, columns=pca_columns)

df_pca.head()

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13
0,-2.073498,-0.525725,0.527998,-1.958679,1.545296,0.652053,0.735141,-2.186569,1.239695,1.293599,-0.551279,0.765817,-1.285435
1,-2.079362,-0.541204,0.525744,-1.999203,1.536834,0.646179,0.756155,-2.207553,1.231171,1.298816,-0.534910,0.766958,-1.331135
2,-2.119141,-0.431553,0.346198,0.174102,1.170845,1.630292,1.816176,-2.111649,1.338851,1.375346,-0.347412,1.318782,-0.707075
3,-2.116627,-0.458279,0.399564,-0.434947,1.289712,1.379757,1.560320,-2.100620,1.329867,1.355656,-0.374544,1.196395,-0.813186
4,-2.107719,-0.458234,0.391929,-0.352940,1.261161,1.395093,1.590811,-2.091631,1.313742,1.345034,-0.406631,1.164314,-0.875687